# Generated by Django 5.0.4 on 2024-04-20 10:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=1500)),
                ('location', models.TextField(default='', max_length=500)),
                ('capacity', models.IntegerField(default=0)),
                ('images', models.ImageField(default='HallImages/default.jpg', upload_to='HallImages')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dean', models.TextField(default='')),
                ('club', models.TextField(default='')),
                ('department', models.TextField(default='')),
                ('eventName', models.TextField(default='')),
                ('eventDescription', models.CharField(default='', max_length=1000)),
                ('startTime', models.DateTimeField(default=datetime.datetime.now)),
                ('endTime', models.DateTimeField(default=datetime.datetime.now)),
                ('approvedStatus', models.BooleanField(default=False)),
                ('remarks', models.CharField(default='', max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_booking', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor_booking', to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hall')),
            ],
        ),
    ]
