# Generated by Django 5.0.4 on 2024-04-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='eventDescription',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='remarks',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
