# Generated by Django 5.0.4 on 2024-04-21 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_eventdescription_alter_booking_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dateOfEvent',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='endTime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
